apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 9
  template:
    metadata:
      labels:
        app: gcp
        track: stable
        version: 1.7.9
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.9
          ports:
            - name: http
              containerPort: 80
            - name: health
              containerPort: 81
          
