apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-rolling-update
spec:
  replicas: 9
  template:
    metadata:
      labels:
        app: gcp
        track: stable
        version: 1.8.1
    spec:
      containers:
        - name: nginx
          image: nginx:1.8.1
          ports:
            - name: http
              containerPort: 80
            - name: health
              containerPort: 81
