apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
	track: stable
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9 #version
        ports:
	        - name: http
            containerPort: 80
