apiVersion: v1
kind: Service
metadata:
  labels:
    app: gcp
    track: stable
    version: 1.7.9
  name: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: gcp
    track: stable
    version: 1.7.9
  type: LoadBalancer
