apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-canary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gcp
        track: canary
        version: 1.8.0
    spec:
      containers:
        - name: nginx
          image: nginx:1.8.0
          ports:
            - name: http
              containerPort: 80
            - name: health
              containerPort: 81
