kind: Service
apiVersion: v1
metadata:
  name: "frontend"
spec:
  selector:
    app: "gcp"
    version: "1.0.0"
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: LoadBalancer
