apiVersion: v1
kind: Service
metadata:
  labels:
    run: gcp-web
  name: gcp-web
  namespace: default
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    run: gcp-web
    type: LoadBalancer
